pipeline:
  name: test1
  identifier: test1
  tags: {}
  projectIdentifier: kushal_test
  orgIdentifier: default
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 10m
        tags: {}
