pipeline:
  name: test inp repro
  identifier: test_inp_repro
  projectIdentifier: testingOPA
  orgIdentifier: DoNotDeleteNikhil3
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: <+input>
        tags: {}
