pipeline:
  name: new-pipeline-test
  identifier: newpipelinetest
  projectIdentifier: Sample
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: js11
        identifier: js11
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo 10
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
          environment:
            environmentRef: Demo
            deployToAll: false
            infrastructureDefinitions:
              - identifier: infra1
                inputs:
                  identifier: infra1
                  type: Pdc
                  spec:
                    hosts: <+input>
        tags: {}
        sendGitStatus:
          enabled: true
          name: ""
