pipeline:
  name: new-pipeline-test
  identifier: newpipelinetest
  projectIdentifier: Sample
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: js11
        identifier: js11
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 10s
          environment:
            environmentRef: Demo
            deployToAll: false
            infrastructureDefinitions:
              - identifier: infra1
                inputs:
                  identifier: infra1
                  type: Pdc
                  spec:
                    hosts: <+input>
        tags: {}
        sendGitStatus:
          enabled: true
          name: kjhfdsj
