pipeline:
  name: test-send-git-status
  identifier: testsendgitstatus
  projectIdentifier: Sample
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s11
        identifier: s11
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 10s
          environment:
            environmentRef: Demo
            deployToAll: false
            infrastructureDefinitions:
              - identifier: infra1
        tags: {}
