pipeline:
  name: pipeline-test
  identifier: pipelinetest
  projectIdentifier: DevTesting
  orgIdentifier: DoNotDeleteNikhil
  tags: {}
  stages:
    - stage:
        name: se22
        identifier: se22
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo 20
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
        sendGitStatus:
          enabled: true
          name: hello
