pipeline:
  name: pipeline03
  identifier: pipeline03
  projectIdentifier: DevTesting
  orgIdentifier: DoNotDeleteNikhil
  tags: {}
  stages:
    - stage:
        name: s2
        identifier: s2
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: FilesUpload
                  name: FilesUpload_1
                  identifier: FilesUpload_1
                  spec: {}
                  timeout: 30m
        tags: {}
