pipeline:
  name: pipeline03
  identifier: pipeline03
  projectIdentifier: DevTesting
  orgIdentifier: DoNotDeleteNikhil
  tags: {}
  stages:
    - stage:
        name: s2
        identifier: s2
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo 10
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
