pipeline:
  name: test-pipeline2
  identifier: testpipeline2
  projectIdentifier: testingOPA
  orgIdentifier: DoNotDeleteNikhil
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 10m
        tags: {}
