pipeline:
  name: test0
  identifier: test0
  projectIdentifier: DonotDeleteNikhil
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: nikhilconnector
        repoName: destorg-repo
        build: <+input>
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo 10
    - stage:
        name: dd
        identifier: dd
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo 10
