pipeline:
  name: error-msg-check
  identifier: errormsgcheck
  tags: {}
  projectIdentifier: testingOPA
  orgIdentifier: DoNotDeleteNikhil3
  stages:
    - stage:
        name: S1
        identifier: S1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - parallel:
                  - step:
                      type: Wait
                      name: Wait_1
                      identifier: Wait_1
                      spec:
                        duration: <+input>
                      failureStrategies:
                        - onFailure:
                            errors:
                              - AllErrors
                            action:
                              type: PipelineRollback
                  - step:
                      type: ShellScript
                      name: ShellScript_1
                      identifier: ShellScript_1
                      spec:
                        shell: Bash
                        executionTarget: {}
                        source:
                          type: Inline
                          spec:
                            script: exit 1
                        environmentVariables: []
                        outputVariables: []
                      timeout: 10m
                      failureStrategies:
                        - onFailure:
                            errors:
                              - AllErrors
                            action:
                              type: PipelineRollback
                            spec:
                              failAll: true
              - step:
                  type: Wait
                  name: Wait_2
                  identifier: Wait_2
                  spec:
                    duration: 10s
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: PipelineRollback
