pipeline:
  name: test-pipeline-22
  identifier: testpipeline22
  tags: {}
  projectIdentifier: testingOPA
  orgIdentifier: DoNotDeleteNikhil3
  stages:
    - stage:
        name: S2
        identifier: S2
        tags: {}
        template:
          templateRef: stage1checknongit
          versionLabel: v1
